version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Africa/Johannesburg
  open-pull-requests-limit: 12
  target-branch: develop
  reviewers:
  - wax911
  ignore:
  - dependency-name: com.squareup.okhttp3:logging-interceptor
    versions:
    - "> 3.12.1"
  - dependency-name: com.squareup.okhttp3:logging-interceptor
    versions:
    - ">= 3.12.3.a, < 3.12.4"
  - dependency-name: com.squareup.okhttp3:logging-interceptor
    versions:
    - ">= 3.13.a, < 3.14"
  - dependency-name: com.squareup.okhttp3:logging-interceptor
    versions:
    - ">= 3.14.a, < 3.15"
  - dependency-name: com.squareup.okhttp3:logging-interceptor
    versions:
    - ">= 4.a, < 5"
  - dependency-name: com.squareup.retrofit2:converter-gson
    versions:
    - "> 2.6.2, < 3"
  - dependency-name: com.squareup.retrofit2:retrofit
    versions:
    - "> 2.6.2, < 3"
