name: android-spotless

on:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - '*'

jobs:
  android-spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run spotless check
        run: ./gradlew spotlessCheck
