name: gradle-dokka

on:
  push:
    branches: [ develop ]

env:
  CI: "true"

jobs:
  gradle-dokka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate docs with dokka
      run: ./gradlew dokkaHtml

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        branch: docs # The branch the action should deploy to.
        folder: library/build/docs/dokka # The folder the action should deploy.
